name: Deploy
on:
  push:
    branches: [main, master]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: codeberg-tiny-lazy
    strategy:
      matrix:
        include:
          - name: chaox
            url: "https://ty3r0x.chaox.ro"
            host: ${{ vars.HOST_CHAOX }}
            port: ${{ vars.PORT_CHAOX }}
            user: ${{ vars.USER_CHAOX }}
            path: ${{ vars.PATH_CHAOX }}
          - name: catto
            url: "https://catto.garden/~ty3r0x"
            host: ${{ vars.HOST_GETIMISKON }}
            port: 22
            user: ${{ vars.USER_GETIMISKON }}
            path: ${{ vars.PATH_GETIMISKON }}
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxml2-utils \
            make \
            perl \
            sed \
            rsync \
            jq
      - uses: actions/checkout@v4
      - name: Install Zola
        env:
          ZOLA_VERSION: "0.22.1"
        run: |
          curl -sL https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv zola /usr/local/bin/
          zola --version
      - name: Build & Convert
        run: |
          sed -i 's|^base_url = .*|base_url = "${{ matrix.url }}"|' config.toml
          make all
      - name: Deploy
        env:
          KEY_CHAOX: ${{ secrets.SSHKEY_CHAOX }}
          KEY_CATTO: ${{ secrets.SSHKEY_GETIMISKON }}
        run: |-
          mkdir -p ~/.ssh
          if [ "${{ matrix.name }}" = "chaox" ]; then
            echo "$KEY_CHAOX" > ~/.ssh/id_rsa
          else
            echo "$KEY_CATTO" > ~/.ssh/id_rsa
          fi
          chmod 600 ~/.ssh/id_rsa
          rsync -avz --delete -e "ssh -p ${{ matrix.port }} -o StrictHostKeyChecking=no" ./public/ ${{ matrix.user }}@${{ matrix.host }}:${{ matrix.path }}/
